### ISSUE TITLE
JWS to JWE usage with SymmetricKey

### ISSUE THREAD

**Issue by jhuet** [kelvinmo/simplejwt#13]
Hello,

First of all, thanks for this JWT library, it looks like to be the easiest one to use that also supports encryption.

I think i'm a bit confused as to how to create a JWE from a JWS though. I keep getting a `Key not found or is invalid` error when decrypting the JWE. Here's how i'm trying to do it :

```php
<?php

    $keys = \SimpleJWT\Keys\KeySet::createFromSecret('secret123');
    $headers_jwt = ['alg' => 'HS512', 'typ' => 'JWT'];
    $claims = [
        'iss' => 'me',
        'iat' => time(),
        'exp' => time() + (24 * 60 * 60),
    ];
    $jwt = new \SimpleJWT\JWT($headers_jwt, $claims);
    $encoded = $jwt->encode($keys);

    $headers_jwe = ['alg' => 'PBES2-HS512+A256KW', 'enc' => 'A256CBC-HS512'];
    $jwe = new \SimpleJWT\JWE($headers_jwe, $encoded);
    $encrypted = $jwe->encrypt($keys);

    $decrypted = $jwe->decrypt($encrypted, $keys, 'PBES2-HS512+A256KW'); // Key not found or is invalid

    $decoded = $jwt->decode($decrypted->getPlaintext(), $keys, 'HS512');
```

Am i missing something regarding keys usage ?

**Comment by kelvinmo** [comment]
`decrypt()` and `decode()` are static functions.  Try:

```php
$decrypted = \SimpleJWT\JWE::decrypt($encrypted, $keys, 'PBES2-HS512+A256KW'); 
$decoded = \SimpleJWT\JWT::decode($decrypted, $keys, 'HS512');
```

**Comment by jhuet** [comment]
Hi @kelvinmo, unfortunately, the output is the same either way.

**Comment by kelvinmo** [comment]
OK.  I've looked at it again, and there is a bug in the code whereby it is inserting a `kid` parameter in the header when it shouldn't (`kid` is only used for asymmetric encryption).  If you comment out line 86 of src/SimpleJWT/Crypt/AESKeyWrap.php, where it says

```php
$headers['kid'] = $key->getKeyId();  // comment out this line
```

it should work

**Comment by jhuet** [comment]
Yes, it works, thanks a lot! Is this an easy fix for you? I'm not very familiar with JWT or your implementation so i'm not sure i could propose a correct PR.

edit: Nevermind, Github didnt update with your fix when i wrote this, so i see it's already done and there was nothing else to take care of on top of removing the line :)

**Comment by kelvinmo** [comment]
I've got a PR prepared at #14.  If it works I can merge it into master

**Comment by makarandchavan** [comment]
Hi,
Thanks for this simple library. I have a similar problem. Getting "SimpleJWT\InvalidTokenException: Key not found or is invalid in SimpleJWT\JWE::decrypt() ". My code is as below and I am trying to decrypt the token from the other party.

```
$set = new \SimpleJWT\Keys\KeySet();
$key = new \SimpleJWT\Keys\RSAKey((array) $private_key, 'php');
$set->add($key);
$jwt = \SimpleJWT\JWE::decrypt($response_data['id_token'], $set, 'RSA-OAEP'); // Key not found or is invalid
```

My Private key format is as below:
{
  "kty": "RSA",
  "d": "xxx",
  "e": "AQAB",
  "n": "yyyy"
}
