### ISSUE TITLE
create jwt with es256 algo and with private key and client_id

### ISSUE THREAD

**Issue by infuginindia** [kelvinmo/simplejwt#16]
Hello Kelvinmo,

I want to generate a JWT, with ES256 algorithm with private key, and client_id in header, may you please let me know how to change below code , I have given you javascript code which is working.
==================================
var private_key = 'MIGHAgEAMBMGByqGfdfdfffffdfdfffG0wawIBAQQg11u3eXyPlKWlTpCnpaq+LfVzsXTlL3WT04KHIvDsHk6hRANCAASOQ4PjYOOzjxXt'
 private_key = "-----BEGIN PRIVATE KEY-----\n" + private_key + "\n-----END PRIVATE KEY-----"

var header = {
  kid: 'fcb746c8ffdf761566516580c2'
}

var payload = {
  iss: '8f33f095d36bfdgfgfgd1ed9742808ca',
  sub: '8f33f095d3fdgdgfd11ed9742808ca',
  aud: 'https://example.talkdeskid.com/oauth/token',
  jti: uuid(),
  exp: Math.floor(Date.now() / 1000) + 300,
  iat: Math.floor(Date.now() / 1000)
}
token = jwt.sign(payload, private_key, {header: header, algorithm: 'ES256'});
=====================================================

// Note 
$headers['alg'] is required
$headers = ['alg' => 'ES256', 'typ' => 'JWT'];
$claims = ['iss' => 'me', 'exp' => 1234567];
$jwt = new SimpleJWT\JWT($headers, $claims);

**Comment by kelvinmo** [comment]
I suspect you will need a better understanding of what a JWT is, what it contains and how it works before attempting to port the code to PHP.  You may wish to peruse the [JWT introduction](https://tools.ietf.org/html/rfc7519) and the standard [RFC 7519](https://tools.ietf.org/html/rfc7519).

You will then be able to map out the header and the payload into a format that is accepted by SimpleJWT (see the README for further instructions).

The only other thing that is different is what to do with the private key.  It appears that the js library allows you to specify the private key directly into the sign function, whereas SimpleJWT requires you to firstly create a key set, add the private key into the key set, then pass the key set into the encode function.
