### ISSUE TITLE
SimpleJWT\InvalidTokenException: Key not found or is invalid in SimpleJWT\JWE::decrypt() 

### ISSUE THREAD

**Issue by kelvinmo** [kelvinmo/simplejwt#17]
Hi,
Thanks for this simple library. I have a similar problem. Getting "SimpleJWT\InvalidTokenException: Key not found or is invalid in SimpleJWT\JWE::decrypt() ". My code is as below and I am trying to decrypt the token from the other party.

```
$set = new \SimpleJWT\Keys\KeySet();
$key = new \SimpleJWT\Keys\RSAKey((array) $private_key, 'php');
$set->add($key);
$jwt = \SimpleJWT\JWE::decrypt($response_data['id_token'], $set, 'RSA-OAEP'); // Key not found or is invalid
```

My Private key format is as below:
{
  "kty": "RSA",
  "d": "xxx",
  "e": "AQAB",
  "n": "yyyy"
}

_Originally posted by @makarandchavan in https://github.com/kelvinmo/simplejwt/issues/13#issuecomment-528420232_

**Comment by kelvinmo** [comment]
That private key format is json, not php.  You can create a RSA key by passing the JSON encoded content as a string (rather than as an array you've provided in the code above), and specifying `json` in the second parameter.

**Comment by makarandchavan** [comment]
Hi,
Thank you. I passed the private key as string formatted JSON but still the same result. I observed behaviour that even if I add a "kid" to my private key, in $set I get different kid automatically generated. This results in a blank $key variable in **decryptKey** function in RSAES.php.

**Comment by makarandchavan** [comment]
Hi, 
As per the suggestions, I think I need to deserailize the token using the private key. Is the \SimpleJWT\JWE::decrypt() function correct to use here for deserializing the token?

**Comment by kelvinmo** [comment]
Yes, you need to use the decrypt() function to decrypt the token.

Please note that kid is automatically generated when you create a private key, unless the parameter `kid` itself is in the JSON.  Otherwise, you can set the kid after creation by using $key->setKeyId('your key id')
