### ISSUE TITLE
Small error in readme

### ISSUE THREAD

**Issue by artifex-media** [kelvinmo/simplejwt#18]
Hi,

There seems to be a small error in the readme where you are referencing to decrypt a JWE:
`$jwt = SimpleJWT\JWT::decrypt('abc.def.ghi.klm.nop', $set, 'PBES2-HS256+A128KW');`

`JWT::decrypt()` is not a method, it should be:
`JWE::decrypt()`

Thank you :)

**Comment by kelvinmo** [comment]
Fixed. Thank you
