### ISSUE TITLE
Not installable on PHP 8.3

### ISSUE THREAD

**Issue by deltaglow** [kelvinmo/simplejwt#191]
### Description

On PHP 8.3 composer install version 0.3 because of requirement: "php": "^8.0"

### Expected behaviour

I am not aware of something what should not work on 8.3, so maybe requirement should be "php": "^8".

**Comment by kelvinmo** [comment]
The constraint "php": "^8.0" should cover PHP 8.3 as shown in this checker: https://jubianchi.github.io/semver-check/#/^8.0/8.3

Simplejwt 0.3 doesn't support PHP8. Please make sure you are installing the latest version of simplejwt (0.9.0) for PHP8 compatibility

**Comment by deltaglow** [comment]
I reinstalled it and you are right, it works. I didn't have gmp plugin, so composer switched to 0.3 version. Sorry for wrong issue ticket.
