### ISSUE TITLE
Dependency issue with Laravel 6

### ISSUE THREAD

**Issue by reedknight** [kelvinmo/simplejwt#24]
Unable to install the package on a `"laravel/framework": "^6.2"` app. Getting the following error when trying to install with composer.

> Problem 1
    - Installation request for kelvinmo/simplejwt ^0.4.0 -> satisfiable by kelvinmo/simplejwt[v0.4.0].
    - Conclusion: remove symfony/console v4.4.10
    - Conclusion: don't install symfony/console v4.4.10
    - kelvinmo/simplejwt v0.4.0 requires symfony/console ~2.8 -> satisfiable by symfony/console[2.8.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.43, v2.8.44, v2.8.45, v2.8.46, v2.8.47, v2.8.48, v2.8.49, v2.8.5, v2.8.50, v2.8.52, v2.8.6, v2.8.7, v2.8.8, v2.8.9].

This package is required with the [googleapis/google-auth-library-php](https://github.com/googleapis/google-auth-library-php/blob/master/composer.json) package.

**Comment by kelvinmo** [comment]
This is a duplicate of #22

**Comment by reedknight** [comment]
The package has installed properly now. The functionality for which it was needed it working. Thank you for updating so quickly.
