### ISSUE TITLE
Wrong namespace in docblocks for keys and crypt

### ISSUE THREAD

**Issue by raegmaen** [kelvinmo/simplejwt#3]
I encountered the problem in the specific case of using `JWT::decode` here I give `\SimpleJWT\Keys\KeySet`, but the docblock requires `\SimpleJWT\SimpleJWT\Keys\KeySet`. 

The docblock itself shows `SimpleJWT\Keys\KeySet`, because of the missing `\` it adds the own namespace `SimpleJWT` to it. There are two options to fix it.
1. Adding the missing `\` to the docblock
2. Removing `SimpleJWT\` from it

I can provide a pull request if I get permissions to push to the repository.

Thanks in advance! And thanks for this library, saved me a lot of time already!

**Comment by kelvinmo** [comment]
Would you be able to fork the repository, work off that, then submit a pull request?

The preference is for documentation blocks to use Fully Qualified Class Names if not in the same namespace, so please add the missing `\`.
