### ISSUE TITLE
$set variable does not have key

### ISSUE THREAD

**Issue by oadekoya12** [kelvinmo/simplejwt#5]
Hi,
I am using the example the [readme](https://github.com/kelvinmo/simplejwt).
For some reason when I want to verify my sign token and getting the following error:

> SimpleJWT\InvalidTokenException: Key not found or is invalid in SimpleJWT\JWT::decode() 
```php
$set = new SimpleJWT\Keys\KeySet();
  $key_private = new SimpleJWT\Keys\RSAKey(file_get_contents([part to the private key]/key.pem', true), 'pem');
$set->add($key_private);
$headers = array('alg' => 'RS256', 'typ' => 'JWT');
$claims = array("iss" => "joe", "exp" => 1300819380, "http://example.com/is_root" => true); //for example
$jwt_hc= new SimpleJWT\JWT($headers, $claims);
$jwt = $jwt_hc->encode($set);
$jwt_decode = SimpleJWT\JWT::decode($jwt, $set, 'RS256');
```

Please I need help.

**Comment by kelvinmo** [comment]
There may be two issues which you may wish to try:

1. In the example above, `$claims` is null.  `$claims` must a least be an empty array.
2. For RSA keys, the KeySet (`$set`) used in encoding is different from the one used for decoding.  The KeySet used for encoding should contain RSA private keys, whereas the KeySet used for decoding should contain public keys.  You can have a look at testGenerateRSA() and testVerifyRSA() in tests/JWTTest.php for examples on how this should work.

**Comment by oadekoya12** [comment]
Hi Kelvinmo,
Thanks for the replay.  I have updated the claim with an example.

Now am having another problem with 

> vendor/kelvinmo/simplejwt/src/SimpleJWT/Crypt/Algorithm.php on line 129

//Code
```
  foreach ($set->getKeys() as $key) {
    $public_key = $key->getPublicKey();
   }
  $jwt_decode = SimpleJWT\JWT::decode($jwt,$public_key, 'RS256');
```

saying that

> Fatal error: Call to undefined method SimpleJWT\Keys\RSAKey::get()

Thanks

**Comment by kelvinmo** [comment]
You'll need to put the public keys into another KeySet, so:

```php
$public_set = new SimpleJWT\Keys\KeySet();
foreach ($set->getKeys() as $key) {
    $public_set->add($key->getPublicKey());
}
$jwt_decode = SimpleJWT\JWT::decode($jwt,$public_set, 'RS256');
```

**Comment by oadekoya12** [comment]
Thanks for everything.
Lastly, I have a remote key that I need to use to verify a response token.

```

$remote_set = new SimpleJWT\Keys\KeySet();
$remote_key ='{"keys":[{
  "kty":"RSA",
    "e":"AQAB",
"n":"ofgWCuLjybRlzo0tZWJjNiuSfb4p4fAkd_wWJcyQoTbji9k0l8W26mPddxHmfHQp-Vaw-4qPCJrcS2mJPMEzP1Pt0Bm4d4QlL-yRT-SFd2lZS-pCgNMsD1W_YpRPEwOWvG6b32690r2jZ47soMZo9wGzjb_7OMg0LOL-bSf63kpaSHSXndS5z5rexMdbBYUsLA9e-KXBdQOS-UTo7WTBEMa2R2CapHg665xsmtdVMTBQY4uDZlxvb3qCo5ZwKh9kG4LT6_I5IhlJH7aGhyxXFvUK-DWNmoudF8NAco9_h9iaGNj8q2ethFkMLs91kzk2PAcDTW9gb54h4FRWyuXpoQ",
    "kid":"RSA"}]}';
$remote_key_set = $remote_set->add(new Keys\RSAKey($remote_key), 'php');
$jwt_decode = SimpleJWT\JWT::decode($jwt,$remote_key_set, 'RS256');

```

I am having a problem $remote_set->add... which returned an error

> Fatal error: Call to a member function getSignature() on string in 
> vendor/kelvinmo/simplejwt/src/SimpleJWT/Keys/KeySet.php on line 114

Thanks

**Comment by kelvinmo** [comment]
`$remote_key` seems to be a decoded version of a JWK set as per RFC 7517.  

If this is the case, you can use load() on the encoded string:

```php
$jwks = json_encode($remote_key);
$remote_set->load($jwks);  // $jwks must be a JSON-encoded string
$jwt_decode = SimpleJWT\JWT::decode($jwt, $remote_set, 'RS256');
```

**Comment by oadekoya12** [comment]
Thanks, It works. I changed the last two lines.
Final Code:
`$remote_set->load($jwks);  
$jwt_decode = SimpleJWT\JWT::decode($jwt, $remote_set, 'RS256');`

**Comment by oadekoya12** [comment]
Revert back.
when I use 
`$remote_set->load($jwks); 
$jwt_decode = SimpleJWT\JWT::decode($jwt, $remote_set, 'RS256');
`
The key could not be validated because am having the error from my log saying
> 
SimpleJWT\InvalidTokenException: Incorrect signature in SimpleJWT\JWT::decode() (line 168 of ..../kelvinmo/simplejwt/src/SimpleJWT/JWT.php).

But when I converted it to PEM and checked it online, it passed signature verification.
`  foreach ($remote_set->getKeys() as $key2){
      $ptest = $key2->getPublicKey();
      //screen output
      dsm($ptest); //in drupal and I got the public key
    }`

or is their a way that I can add a public key to "KeySet" and use it to verify an ID Token?

**Comment by kelvinmo** [comment]
A few things which may help.

Firstly, you may want to check whether the keys you are getting are public keys.  Try:

```php
foreach ($remote_key->getKeys() as $key) {
    print $key->isPublic();
}
```

If the function comes out as false, then you have a horrible situation of someone placing their private keys online.

Secondly, if $remote_set contains multiple RSA keys, you will need to specify which one of those keys should be used to verify the signature, using the $kid parameter in the decode function.  Otherwise it will choose the one that matches the kid claim in the JWT or if that doesn't exist, the first RSA key in $remote_set.

Thirdly, check that the openssl module in php is working.  Try running the test suite in the tests directory using phpunit.

**Comment by oadekoya12** [comment]
Hi kelvinmo,
1. the result of "$key->isPublic()" is "TRUE".
2. After "$remote_set->load($remote_key); ", I cannot get the kid with "$remote_set->getKeyId()" base on the following error...

> Fatal error: Call to undefined method SimpleJWT\Keys\KeySet::getKeyId() in 

I need key set command for JWK.

Thanks
Olawale

**Comment by kelvinmo** [comment]
The key ID can be obtained directly from the JSON representation a JWK, using the `kid` property.  In the example JWK above (https://github.com/kelvinmo/simplejwt/issues/5#issuecomment-372658414), the key ID is `RSA`.

**Comment by oadekoya12** [comment]
Hi kelvinmo,
I have the following error.
> Notice: Undefined property: SimpleJWT\Crypt\OpenSSLSig::$getKeyCriteria in SimpleJWT\JWT::decode() (line 164 of... ...simplejwt/src/SimpleJWT/JWT.php)
   SimpleJWT\InvalidTokenException: Incorrect signature in SimpleJWT\JWT::decode() (line 182 of... simplejwt/src/SimpleJWT/JWT.php)

`
    $key_remote_json = json_decode($remote_key, true);
    $key_remote_json = $key_remote_json['keys'][0];
    $key_jwk = new SimpleJWT\Keys\RSAKey($key_remote_json, 'php');
     
    $set = new SimpleJWT\Keys\KeySet();

    $set->add($key_pem);
    $set->add($key_jwk);

    $jwt = SimpleJWT\JWT::decode($jwt_remote, $set,'RS256', $key_jwk->getSignature());
`
**I realise "$key->toPEM()" is not current when i check it with the JWT.io website.**
Thanks
Olawale

**Comment by kelvinmo** [comment]
I'm afraid I don't understand this.  You will need to send through the full stacktrace as the line numbers do not match my source.
